- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 28800 # 8 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Medical
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    eyes: ClothingEyesGlassesBrigmedic
    ears: ClothingHeadsetBrigmedic
    neck: ClothingNeckTieRed
    pocket1: WeaponPistolMk58
    mask: ClothingMaskBreathMedicalSecurity
    id: BrigmedicPDA
    gloves: ClothingHandsGlovesNitrile
    belt: ClothingBeltBrigmedicFilled
  storage:
    back:
    - Flash
    - MagazinePistol
